version: '3.8'

services:
  api:
    container_name: qr-api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/qr
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    container_name: qr-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    name: qr-tracker-mongodb-data

networks:
  app-network:
    name: qr-tracker-network
    driver: bridge